### PR TITLE
adding linkedin and mail icons and settings

### PR DESCRIPTION
**Pull request by kevin-verschaeve**
This add 2 icons and settings for LinkedIn and personnal mail in the theme configuration

### CODE REVIEW

**Comment by rodica-andronache** [comment]
Hi @kevin-verschaeve ,

Thank you so much for this contribution. I only need one change before I can merge it. I would need you to remove the default values for this two new settings. We can't add it with default values, because the theme is already used by a number of users.

**Comment by kevin-verschaeve** [comment]
Hi,
Thanks for reviewing, I have updated the PR, can you tell me if it is ok now ?

**Comment by rodica-andronache** [comment]
Hi @kevin-verschaeve ,

You also had to remove the default values from functions.php, for each of the sections, but it's a small change, we'll do it. 
Thanks again for contributing :)

**Comment by kevin-verschaeve** [comment]
Sorry, I was thinking that only in footer.php was blocking.

Thanks for merging ! :smile:

**Pull request merged**
